#! /usr/bin/env node

var callback = require('../');

callback({ip: '127.0.0.1'}, function(err, server) {
  console.log('TRY: curl', server.url);

  server.on('callback', function(data) {
    console.dir(data);
  });
})
